### ISSUE TITLE
'x-ua-compatible' header should not be a requirement

### ISSUE THREAD

**Issue by jsmad** [sonarwhal/sonarwhal#668]
An error is produced when the x-ua-compatible header is not set. This x-ua-compatible meta header is a hack for IE only, such browser-specific hacks should not produce errors. 

Considering the IE browser is used by such a small minority, it clearly shouldn't be producing an entire error when this meta tag is missing.

**Comment by alrra** [comment]
@jsmad See #666.

**Comment by alrra** [comment]
and sonarwhal/sonarwhal.com#309.

**Comment by jsmad** [comment]
Let me guess, this project is somehow "sponsored" by Microsoft ;)

Otherwise this garbage shouldn't even be here, let alone produce an error.

**Comment by alrra** [comment]
> Otherwise this garbage shouldn't even be here, let alone produce an error.

@jsmad As specified in the [rule's documentation](https://sonarwhal.com/docs/user-guide/rules/highest-available-document-mode/#cantherulebeconfigured), if you provide some context to `sonarwhal`, the rule will actually complain and suggest not sending the `X-UA-Compatible` HTTP header or using the meta tag.

> Let me guess, this project is somehow "sponsored" by Microsoft ;)

As I [previously stated](https://github.com/sonarwhal/sonarwhal.com/issues/309#issuecomment-346082805):

> the idea with `sonarwhal` is to suggest whatever is best for the [user's needs](https://sonarwhal.com/docs/user-guide/#browserconfiguration), but for that the user has to provide `sonarwhal` with some information (e.g.: the support matrix).

As with this rule, because of interoperability, we also have a what you may call a [Apple specific rule](https://sonarwhal.com/docs/user-guide/rules/apple-touch-icons/#page-heading) ([that in the future might suggest removing things](https://github.com/sonarwhal/sonarwhal/issues/661)).

**Comment by alrra** [comment]
@jsmad Also note that you can [configure `sonarwhal` to only run the rules that you consider make the most sense for your particular case](https://sonarwhal.com/docs/user-guide/#ruleconfiguration).

**Comment by molant** [comment]
> Let me guess, this project is somehow "sponsored" by Microsoft ;)

@jsmad the project belongs to the JS Foundation. The governance model welcomes anyone interested in shaping the future of the tool.

Maybe you could take a look at the other open issues and provide feedback or, even better, a pull request?

**Comment by jsmad** [comment]
X-UA-Compatible is a Microsoft hack and the scanner should give an error when it detects it, so that web developers remove it from their code. Amazingly, it does the opposite right now.

All the above are good excuses, but at the end of the day, they are just that, excuses. 

You require a useless header that is a custom hack for a browser that has less than 10% of market share (and falling), just laughable... :)

**Comment by alrra** [comment]
> give an error when it detects it... Amazingly, it does the opposite right now.

Again, as [I stated before](https://github.com/sonarwhal/sonarwhal/issues/668#issuecomment-346284002), and as [it's stated in the documentation](https://sonarwhal.com/docs/user-guide/rules/highest-available-document-mode/#cantherulebeconfigured), what rules flag as errors depends on the context, so if the user's browser matrix does not include IE 8/9/10, **`sonarwhal` it will tell the user to not send the HTTP header and remove the meta tag.**

`sonarwhal`, as with other projects (e.g.: `Autoprefixer`, `Stylelint`, `babel-preset-env`), uses [`browserslist`](https://github.com/ai/browserslist), and [its defaults (although uses are asked about that from the beginning)](https://github.com/sonarwhal/sonarwhal.com/issues/309#issuecomment-346082805), defaults that currently include IE 10. 

Related to the [online scanner](https://sonarwhal.com/scanner/), as stated on the website, [it's currently in preview](https://user-images.githubusercontent.com/1223565/33226105-73d3aaf0-d13a-11e7-821f-1240fc0a39fe.png), so right now it doesn't allow configurations as we didn't have the time to implement that part. However, related to that, we are discussing changing the defaults in https://github.com/sonarwhal/sonarwhal.com/issues/309 (issue [I pointed you to even from my first comment](https://github.com/sonarwhal/sonarwhal/issues/668#issuecomment-346277688), but you seemed to ignore, and instead of contributing in a productive way to that discussion, you just continued with your ranting here).).

---

@jsmad Please see out [code of conduct](https://js.foundation/community/code-of-conduct) (especially the `Be respectful` part).
