### ISSUE TITLE
IMG tag that points to a PHP script produces a mime type error

### ISSUE THREAD

**Issue by jsmad** [sonarwhal/sonarwhal#669]
The scanner does not properly detect requests to PHP scripts that return an image.

For example, the request for the following image:
```html
<img width="16" height="16" alt="avatar" src="https://example.tld/avatar.php?height=16">
```

Returns the following error:
```'content-type' header should have media type 'application/x-httpd-php' (not 'image/gif') ```

Instead, it should expect that an IMG tag could potentially return a content-type related to an image, like "image/gif".

**Comment by alrra** [comment]
> https://example.tld/avatar.php?height=16

@jsmad Can you provide an example that works? Thanks!

> https://example.tld/avatar.php?height=16

In this case, since that URL doesn't work, and no data is returned, `sonarwhal` tries to best determine what type of file it is, and since it cannot look at the data returned, it tries to use the extension.

If the URL actually returned a valid GIF it should suggest `image/gif`.

**Comment by alrra** [comment]
Closing for now. I'm happy to reopen this if more information is provided.
