### ISSUE TITLE
Lighthouse integration?

### ISSUE THREAD

**Issue by hbakhtiyor** [sonarwhal/sonarwhal#721]
would be nice to see lighthouse integration for another rules, for not reinventing the wheel

**Comment by alrra** [comment]
> for not reinventing the wheel

@hbakhtiyor We are [actually contributing](https://github.com/GoogleChrome/chrome-launcher/pulls?q=is%3Apr+author%3Amolant) to and syncing with the Lighthouse team from time to time on areas that may overlap, and if and where it make sense, we will try to recommend the same things. 

However, since:

   * Lighthouse is built to work with Chrome only, and doesn't concentrate on a specific problem (like other tools do, e.g: `SSL Labs`, `Snyk`, etc.)
   * in general, the projects are not "compatible" with each other as they have different scopes and approach things differently (e.g.: `sonarwhal` adapts and may suggest different things depending on the [context](https://sonarwhal.com/docs/user-guide/further-configuration/browser-context/) and the user's needs, is highly configurable and doesn't have a scoring system, [supports multiple browsers](https://sonarwhal.com/docs/user-guide/concepts/connectors/#built-inconnectorsandplatformsupport) not just Chrome, etc).

it's unlikely an integration can/will happen.
