### ISSUE TITLE
Brotli resources should not be marked as "Should be served compressed with Zopfli"

### ISSUE THREAD

**Issue by staabm** [sonarwhal/sonarwhal#913]
running a report with the scanner https://sonarwhal.com/scanner/a4ef16bf-3171-467f-b779-ba57fd3a82c1#performance

shows us some resources in the performance section for which a error is displayed, e.g.

![grafik](https://user-images.githubusercontent.com/120441/37759767-ea6b66f4-2db4-11e8-9b01-6b000ad60cea.png)

since we serve our website with brotli, I dont think this error is helpful or correct.

**Comment by alrra** [comment]
> since we serve our website with brotli, I dont think this error is helpful or correct.

[Brotli is HTTPS only](https://medium.com/@yoavweiss/well-the-technical-reason-for-brotli-being-https-only-is-that-otherwise-there-s-a-very-high-508f15f0ad95), so over HTTP the best thing one can do is serve things compressed using Zopfli, and that is the reason why Zopfli is suggested.

But yes, I do agree we should make it more clear that the suggestion for Zopfli is for when things are served over HTTP not HTTPS (see also: #914).

**Comment by staabm** [comment]
the url mentioned in the error screen is a https url..?

**Comment by alrra** [comment]
> the url mentioned in the error screen is a https url..?

The rule analyzes different aspects, so it makes a few different requests besides the initial one, but it always uses the original URL when printing the error which is why in the above happens.

[I'll look over it](914), and fix it, sorry for the confusion.

**Comment by molant** [comment]
Also a browser might not understand brotli at all and thus zopfli should be used even over https.
